### ISSUE TITLE
Regression in release-4.0 branch

### ISSUE THREAD

**Issue by NicoNes** [jakartaee/rest#1165]
Hi @spericas,

I've just noticed that cookie builder introduced in 3.1.0 by this PR https://github.com/jakartaee/rest/pull/895  no longer exist in release-4.0 branch (https://github.com/jakartaee/rest/commit/ae1f6ef7f4db9957079b8c383041a4537f33f35b).  
Was this rollback made on purpose ?

PS: Same thing for changes introduces by this PR https://github.com/jakartaee/rest/pull/995

-- Nicolas

**Comment by NicoNes** [comment]
Hey @spericas ,

Well, I did not check all files modified by [this commit](https://github.com/jakartaee/rest/commit/ae1f6ef7f4db9957079b8c383041a4537f33f35b) but it seems that at least the following validated PRs from 3.1 are missing in the `release-4.0` branch:

- https://github.com/jakartaee/rest/pull/895
- https://github.com/jakartaee/rest/pull/995
- https://github.com/jakartaee/rest/pull/863
- https://github.com/jakartaee/rest/pull/1010
- https://github.com/jakartaee/rest/pull/1028
- https://github.com/jakartaee/rest/pull/948

Since the `release-4.0` branch does not contain merged code for now (only init commit for what I saw) and due to this big amount of missing code maybe it will be better/simpler to  either:
- create and init a brand-new `4.0` branch from master.
- revert [this commit](https://github.com/jakartaee/rest/commit/ae1f6ef7f4db9957079b8c383041a4537f33f35b) and work again on it

WDYT ?  

-- Nicolas

**Comment by spericas** [comment]
On Jul 28, 2023, at 6:37 PM, NicoNes ***@***.***> wrote:



Hey @spericas<https://urldefense.com/v3/__https://github.com/spericas__;!!ACWV5N9M2RV99hQ!I8BOeHhiSfeEqLof1Lzc3eJD_BwW9mKz6DcGKQ0zR0UGQC6oORTVSvqnZewewi1M3ExQc00QdO-0fYcSH2KMgJPwsNCdCeBp-aA$> ,

Well, I did not check all files modified by this commit<https://urldefense.com/v3/__https://github.com/jakartaee/rest/commit/ae1f6ef7f4db9957079b8c383041a4537f33f35b__;!!ACWV5N9M2RV99hQ!I8BOeHhiSfeEqLof1Lzc3eJD_BwW9mKz6DcGKQ0zR0UGQC6oORTVSvqnZewewi1M3ExQc00QdO-0fYcSH2KMgJPwsNCd7jxXb-I$> but it seems that at least the following validated PRs from 3.1 are missing in the release-4.0 branch:

  *   #895<https://urldefense.com/v3/__https://github.com/jakartaee/rest/pull/895__;!!ACWV5N9M2RV99hQ!I8BOeHhiSfeEqLof1Lzc3eJD_BwW9mKz6DcGKQ0zR0UGQC6oORTVSvqnZewewi1M3ExQc00QdO-0fYcSH2KMgJPwsNCdSYyQylU$>
  *   #995<https://urldefense.com/v3/__https://github.com/jakartaee/rest/pull/995__;!!ACWV5N9M2RV99hQ!I8BOeHhiSfeEqLof1Lzc3eJD_BwW9mKz6DcGKQ0zR0UGQC6oORTVSvqnZewewi1M3ExQc00QdO-0fYcSH2KMgJPwsNCdYBIgQ-g$>
  *   #863<https://urldefense.com/v3/__https://github.com/jakartaee/rest/pull/863__;!!ACWV5N9M2RV99hQ!I8BOeHhiSfeEqLof1Lzc3eJD_BwW9mKz6DcGKQ0zR0UGQC6oORTVSvqnZewewi1M3ExQc00QdO-0fYcSH2KMgJPwsNCdoGtrge0$>
  *   #1010<https://urldefense.com/v3/__https://github.com/jakartaee/rest/pull/1010__;!!ACWV5N9M2RV99hQ!I8BOeHhiSfeEqLof1Lzc3eJD_BwW9mKz6DcGKQ0zR0UGQC6oORTVSvqnZewewi1M3ExQc00QdO-0fYcSH2KMgJPwsNCdAfa10Lg$>
  *   #1028<https://urldefense.com/v3/__https://github.com/jakartaee/rest/pull/1028__;!!ACWV5N9M2RV99hQ!I8BOeHhiSfeEqLof1Lzc3eJD_BwW9mKz6DcGKQ0zR0UGQC6oORTVSvqnZewewi1M3ExQc00QdO-0fYcSH2KMgJPwsNCdZ7BqsEI$>
  *   #948<https://urldefense.com/v3/__https://github.com/jakartaee/rest/pull/948__;!!ACWV5N9M2RV99hQ!I8BOeHhiSfeEqLof1Lzc3eJD_BwW9mKz6DcGKQ0zR0UGQC6oORTVSvqnZewewi1M3ExQc00QdO-0fYcSH2KMgJPwsNCdWeft7qU$>

Since the release-4.0 branch does not contain merged code for now (only init commit for what I saw) and due to this big amount of missing code maybe it will be better/simpler to either:

  *   create and init a brand-new 4.0 branch from master.
  *   revert this commit<https://urldefense.com/v3/__https://github.com/jakartaee/rest/commit/ae1f6ef7f4db9957079b8c383041a4537f33f35b__;!!ACWV5N9M2RV99hQ!I8BOeHhiSfeEqLof1Lzc3eJD_BwW9mKz6DcGKQ0zR0UGQC6oORTVSvqnZewewi1M3ExQc00QdO-0fYcSH2KMgJPwsNCd7jxXb-I$> and work again on it

 That’s unfortunate :( Without looking at the details as you have, your proposal seems reasonable to me, as long as we don’t drop anything from the new branch.

 Interested in creating a PR for this? Thanks.

— Santiago

**Comment by NicoNes** [comment]
@spericas Yep, I'm working in it.
